.\obj\attm_util128.o: ..\..\sdk\ble_stack\com\profiles\FCC0\util\attm_util128.c
.\obj\attm_util128.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdint.h
.\obj\attm_util128.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\string.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ble\hl\gatt\att.h
.\obj\attm_util128.o: ..\..\sdk\plactform\core_modules\common\api\co_error.h
.\obj\attm_util128.o: ..\..\sdk\plactform\core_modules\common\api\co_utils.h
.\obj\attm_util128.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stddef.h
.\obj\attm_util128.o: ..\..\sdk\plactform\core_modules\common\api\co_bt.h
.\obj\attm_util128.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdbool.h
.\obj\attm_util128.o: ..\..\sdk\plactform\core_modules\common\api\co_lmp.h
.\obj\attm_util128.o: ..\..\sdk\plactform\core_modules\common\api\co_bt.h
.\obj\attm_util128.o: ..\..\sdk\plactform\core_modules\common\api\co_hci.h
.\obj\attm_util128.o: .\config\rwip_config.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\com\rwble\rwble_config.h
.\obj\attm_util128.o: .\config\rwip_config.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\com\rwble_hl\rwble_hl_config.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\com\rwble_hl\rwble_hl_error.h
.\obj\attm_util128.o: .\config\rwprf_config.h
.\obj\attm_util128.o: ..\..\sdk\plactform\arch\compiler\compiler.h
.\obj\attm_util128.o: ..\..\sdk\plactform\core_modules\common\api\co_math.h
.\obj\attm_util128.o: C:\Keil_v5\ARM\ARMCC\Bin\..\include\stdlib.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ble\hl\gatt\gattm\gattm.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ble\hl\gatt\attm\attm_db.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ke\ke_task.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ke\ke_msg.h
.\obj\attm_util128.o: ..\..\sdk\plactform\arch\arch.h
.\obj\attm_util128.o: ..\..\sdk\plactform\arch\ll\ll.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ke\ke_config.h
.\obj\attm_util128.o: ..\..\sdk\plactform\core_modules\common\api\co_list.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ble\hl\gatt\attm\attm.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ble\hl\gatt\gattm\gattm_task.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\com\rwip\api\rwip_task.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ke\ke_timer.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ke\ke_mem.h
.\obj\attm_util128.o: ..\..\sdk\plactform\driver\uart\uart.h
.\obj\attm_util128.o: .\config\user_config.h
.\obj\attm_util128.o: ..\..\sdk\ble_stack\inc\ble\hl\gatt\attc\../gattm/gattm_int.h
